### ISSUE TITLE
小助手改成Ture之后程序闪退

### ISSUE THREAD

**Issue by BBHIMW** [anosora233/richi-console#21]
纯萌新，小助手改成Ture之后程序闪退，基于mitmproxy的中间人攻击方式使用mahjong-helper会导致冲突

**Comment by anosora233** [comment]
遵从 JSON 格式，应为小写的 `true`

**Comment by BBHIMW** [comment]
> 遵从 JSON 格式，应为小写的 `true`

是小写，还是闪退，是小助手位置或代理需要什么要求吗

**Comment by anosora233** [comment]
> > 遵从 JSON 格式，应为小写的 `true`
> 
> 是小写，还是闪退，是小助手位置或代理需要什么要求吗

请在命令行下启动，并附上报错。

**Comment by BBHIMW** [comment]
> > > 遵从 JSON 格式，应为小写的 `true`
> > 
> > 
> > 是小写，还是闪退，是小助手位置或代理需要什么要求吗
> 
> 请在命令行下启动，并附上报错。

Traceback (most recent call last):
  File "mhmp.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "mhm\__main__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "mhm\common.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "mhm\addon.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "mhm\config.py", line 107, in <module>
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 4 column 14 (char 46)
[22264] Failed to execute script 'mhmp' due to unhandled exception!

**Comment by anosora233** [comment]
你是否将 `true` 错误拼写为 `ture` ?
另外请附上配置文件内容

**Comment by BBHIMW** [comment]
> 你是否将 `true` 错误拼写为 `ture` ?
> 另外请附上配置文件内容 

是的，已解决，谢谢。
